# Generated by Django 3.0.8 on 2020-07-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_auto_20200725_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='ending_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='starting_date',
            field=models.DateField(),
        ),
    ]
