# Generated by Django 3.0.8 on 2020-07-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0008_auto_20200728_0841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='leave_accrual',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='leave_balance',
        ),
        migrations.AddField(
            model_name='user',
            name='leave_accrual',
            field=models.PositiveSmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='user',
            name='leave_balance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
