# Generated by Django 3.0.8 on 2020-07-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0009_auto_20200729_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
