# Generated by Django 3.0.8 on 2020-07-31 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0010_auto_20200730_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='approved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approves', to=settings.AUTH_USER_MODEL),
        ),
    ]
