# Generated by Django 3.0.8 on 2020-07-31 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0011_leave_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
