# Generated by Django 3.0.8 on 2020-07-31 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0013_leave_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='is_denied',
            field=models.BooleanField(default=False),
        ),
    ]
